<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FFE-Pavankumar-Hebsur-FFE241" failures="0" tests="2" name="learning.ErrorValidationTest" time="45.702" errors="1" timestamp="2024-02-06T14:46:56 IST" skipped="0">
  <testcase classname="learning.ErrorValidationTest" name="loginErrorValidation" time="21.633">
    <error message="
Couldn&#039;t find a constructor in class com.sun.net.httpserver.Authenticator$Retry" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Couldn't find a constructor in class com.sun.net.httpserver.Authenticator$Retry
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:57)
at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:60)
at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:28)
at org.testng.internal.BaseTestMethod.computeRetryAnalyzerInstanceToUse(BaseTestMethod.java:848)
at org.testng.internal.BaseTestMethod.getRetryAnalyzerConsideringMethodParameters(BaseTestMethod.java:816)
at org.testng.internal.BaseTestMethod.getRetryAnalyzer(BaseTestMethod.java:680)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:550)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:726)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </error>
  </testcase> <!-- loginErrorValidation -->
  <testcase classname="learning.ErrorValidationTest" name="productErrorValidation" time="24.069"/>
</testsuite> <!-- learning.ErrorValidationTest -->
